#!/usr/bin/env php
<?php

require __DIR__.'/bootstrap.php';

$config = [
    'id' => '__yii2ext__-cli-test',
    'basePath' => __DIR__,
    'components' => [
        'db' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host='.$_ENV['DB_HOST'].';dbname='.$_ENV['DB_DATABASE'],
            'username' => $_ENV['DB_USERNAME'],
            'password' => $_ENV['DB_PASSWORD'],
            'charset' => $_ENV['DB_CHARSET'],
        ],
    ],
    'controllerMap' => [
        'migrate' => [
            'class' => 'yii\console\controllers\MigrateController',
            'migrationPath' => null,
            'migrationNamespaces' => [
            ],
        ],
    ],
];

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
