version: '2'
networks:
  project:
    external: false
volumes:
  redis_data:
  mysql_data:
  composer_home:
services:
  redis:
    image: redis:4.0.12-alpine
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      - project
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - redis_data:/data
  mysql:
    image: mysql:5.7.24
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - project
    volumes:
      - ./mysql/zz.cnf:/etc/mysql/conf.d/zz.cnf
      - ./mysql/init.d/:/docker-entrypoint-initdb.d/
      - mysql_data:/var/lib/mysql
  php-fpm:
    build:
      context: .
      dockerfile: ./php-fpm/Dockerfile
      args:
        X_GID: ${X_GID}
        X_UID: ${X_UID}
    networks:
      - project
    volumes:
      - ..:/project
      - composer_home:/tmp/composer
  nginx:
    image: nginx:1.14.2-alpine
    command: /bin/sh -c "envsubst '$$X_DOMAIN' < /etc/nginx/project/sites.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    environment:
      X_DOMAIN: ${X_DOMAIN}
    networks:
      - project
    volumes:
      - ./nginx:/etc/nginx/project
      - ../dev/web:/project/dev/web
